import clsx from "clsx";
import type { ReactNode } from "react";
import { ArrowDown, CircleDot, FlaskConical, Info, TriangleAlert } from "lucide-react";
import type { DataSource, Priority } from "../../types";

export type Tone = "neutral" | "brand" | "info" | "success" | "warning" | "danger" | "water" | "energy" | "crop" | "market" | "resource";

const tones: Record<Tone, string> = {
  neutral: "bg-sunken text-ink-muted",
  brand: "bg-brand-50 text-brand-700",
  info: "bg-info-soft text-info",
  success: "bg-success-soft text-success",
  warning: "bg-warning-soft text-warning",
  danger: "bg-danger-soft text-danger",
  water: "bg-water-soft text-water",
  energy: "bg-energy-soft text-energy",
  crop: "bg-crop-soft text-crop",
  market: "bg-market-soft text-market",
  resource: "bg-resource-soft text-resource",
};

interface BadgeProps {
  tone?: Tone;
  icon?: ReactNode;
  children: ReactNode;
  className?: string;
  title?: string;
}

export function Badge({ tone = "neutral", icon, children, className, title }: BadgeProps) {
  return (
    <span
      title={title}
      className={clsx(
        "inline-flex items-center gap-1 rounded-md px-1.5 py-0.5 text-[11px] font-medium leading-4 whitespace-nowrap",
        tones[tone],
        className,
      )}
    >
      {icon}
      {children}
    </span>
  );
}

const sourceLabels: Record<DataSource, { label: string; hint: string }> = {
  demo: { label: "Demo data", hint: "Fictional demonstration data for the prototype." },
  simulated: { label: "Simulated sensor", hint: "Generated by the simulation layer. No physical sensor is connected." },
  indicative: { label: "Indicative estimate", hint: "An estimate for planning only, not a guaranteed value." },
  prototype: { label: "Prototype value", hint: "Illustrative value used to demonstrate the concept." },
  live: { label: "Live", hint: "Connected to a live data source." },
};

/** Honest labelling of where a number comes from (spec §59). */
export function SourceBadge({ source, className }: { source: DataSource; className?: string }) {
  const { label, hint } = sourceLabels[source];
  return (
    <Badge
      tone={source === "live" ? "success" : "neutral"}
      icon={<FlaskConical aria-hidden className="size-3" />}
      title={hint}
      className={clsx("font-normal", className)}
    >
      {label}
    </Badge>
  );
}

const priorityStyle: Record<Priority, { tone: Tone; label: string; icon: ReactNode }> = {
  high: { tone: "danger", label: "High priority", icon: <TriangleAlert aria-hidden className="size-3" /> },
  medium: { tone: "warning", label: "Medium", icon: <CircleDot aria-hidden className="size-3" /> },
  low: { tone: "neutral", label: "Low", icon: <ArrowDown aria-hidden className="size-3" /> },
};

export function PriorityBadge({ priority }: { priority: Priority }) {
  const p = priorityStyle[priority];
  return (
    <Badge tone={p.tone} icon={p.icon}>
      {p.label}
    </Badge>
  );
}

export function InfoNote({ children, className }: { children: ReactNode; className?: string }) {
  return (
    <p className={clsx("flex gap-2 text-[12px] leading-5 text-ink-muted", className)}>
      <Info aria-hidden className="mt-0.5 size-3.5 shrink-0" />
      <span>{children}</span>
    </p>
  );
}
